# Generated by Django 4.0.5 on 2022-06-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_address_alter_user_end_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "base_manager_name": "data",
                "default_manager_name": "data",
                "get_latest_by": "created",
                "ordering": ["-created"],
                "verbose_name": "Nutzer",
                "verbose_name_plural": "Nutzer",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="customer_number",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
