# Generated by Django 4.0.5 on 2022-06-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_options_user_customer_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="customer_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Kundennummer"
            ),
        ),
    ]
