# Generated by Django 4.0.5 on 2022-06-11 23:57

import django.core.validators
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='Notizen'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Die Telefonnummer muss in folgendem Format eingegeben werden: '+999999999'. Bis zu 15 Zeichen sind erlaubt.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zoom_link',
            field=models.URLField(blank=True, null=True, verbose_name='Zoom-Link'),
        ),
    ]
