# Generated by Django 4.0.5 on 2022-06-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_notes_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ablauf-Datum'),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start-Datum'),
        ),
    ]
