# Generated by Django 4.0.5 on 2022-06-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_paarbox_date_user_paarbox_handed_over_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paarbox_sent',
            field=models.BooleanField(default=False, verbose_name='versendet'),
        ),
    ]
