# Generated by Django 4.0.6 on 2022-10-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer',
            field=models.CharField(max_length=70, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lead',
            field=models.CharField(default='', max_length=70),
        ),
    ]
