# Generated by Django 4.1.5 on 2023-01-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_customer_user_lead"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="customer",
            new_name="contact_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lead",
        ),
        migrations.AddField(
            model_name="user",
            name="lead_id",
            field=models.CharField(max_length=70, null=True),
        ),
    ]
