# Generated by Django 4.1.5 on 2023-01-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_rename_customer_user_contact_id_remove_user_lead_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="customer_number",
        ),
    ]
