# Generated by Django 4.1.5 on 2023-01-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_alter_user_forum_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="user",
            name="paarbox_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="paarbox_handed_over",
        ),
        migrations.RemoveField(
            model_name="user",
            name="paarbox_present",
        ),
        migrations.RemoveField(
            model_name="user",
            name="paarbox_sent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="street",
        ),
        migrations.RemoveField(
            model_name="user",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="user",
            name="bought_membership",
            field=models.BooleanField(default=False, verbose_name="Akademie Beziehungskit"),
        ),
        migrations.AddField(
            model_name="user",
            name="bought_teaser",
            field=models.BooleanField(default=False, verbose_name="Beziehungs1x1"),
        ),
    ]
