# Generated by Django 4.1.6 on 2023-02-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_remove_user_city_remove_user_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="forum_name",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="Forumname"
            ),
        ),
    ]
