# Generated by Django 4.2.4 on 2023-08-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_alter_user_forum_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_member_new",
            field=models.BooleanField(null=True, verbose_name="Aktives Mitglied"),
        ),
    ]
