# Generated by Django 4.2.4 on 2023-10-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_alter_user_username_user_unique_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_view_appointments",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_forum",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="can_view_zoom_link",
            field=models.BooleanField(default=False),
        ),
    ]
