# Generated by Django 4.2.4 on 2023-10-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_user_can_view_appointments_user_can_view_forum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="can_view_appointments",
            field=models.BooleanField(default=False, verbose_name="Termine werden angezeigt"),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_view_forum",
            field=models.BooleanField(default=False, verbose_name="Forum wird angezeigt"),
        ),
        migrations.AlterField(
            model_name="user",
            name="can_view_zoom_link",
            field=models.BooleanField(default=False, verbose_name="Zoom Link wird angezeigt"),
        ),
    ]
