# Generated by Django 4.2.4 on 2023-08-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_rename_active_member_new_user_active_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="active_member",
            field=models.BooleanField(default=False, verbose_name="Aktive Mitgliedschaft"),
            preserve_default=False,
        ),
    ]
