# Generated by Django 4.2.4 on 2023-10-08 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_alter_user_can_view_appointments_and_more"),
    ]

    operations = []
