# Generated by Django 4.2.4 on 2023-10-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_alter_user_active_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="active_member",
            field=models.BooleanField(default=False, verbose_name="Aktive Mitgliedschaft"),
        ),
    ]
