# Generated by Django 4.0.5 on 2022-06-11 09:25

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_quill.fields
from django.conf import settings
from django.db import migrations, models

import webapp.storages


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('concealed', models.BooleanField(default=False, editable=False)),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('content', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Inhalt')),
            ],
            options={
                'verbose_name': 'Unterseite',
                'verbose_name_plural': 'Unterseiten',
                'ordering': ['url'],
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'data',
                'default_manager_name': 'data',
            },
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('concealed', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('description', django_quill.fields.QuillField(blank=True, null=True)),
                ('thumbnail', models.ImageField(storage=webapp.storages.PrivateMediaStorage(), upload_to='', verbose_name='Vorschaubild')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurse',
                'ordering': ['name'],
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'data',
                'default_manager_name': 'data',
            },
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('concealed', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('thumbnail', models.ImageField(storage=webapp.storages.PrivateMediaStorage(), upload_to='', verbose_name='Vorschaubild')),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod_next', to='application.module', verbose_name='Nach')),
                ('prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod_prev', to='application.module', verbose_name='Vor')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.training')),
            ],
            options={
                'verbose_name': 'Kapitel',
                'verbose_name_plural': 'Kapitel',
                'ordering': ['name'],
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'data',
                'default_manager_name': 'data',
            },
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('concealed', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('thumbnail', models.ImageField(storage=webapp.storages.PrivateMediaStorage(), upload_to='', verbose_name='Vorschaubild')),
                ('file', models.FileField(storage=webapp.storages.PrivateMediaStorage(), upload_to='', verbose_name='Datei')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.module')),
                ('next', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_next', to='application.media', verbose_name='Nach')),
                ('prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_prev', to='application.media', verbose_name='Vor')),
            ],
            options={
                'verbose_name': 'Lektion',
                'verbose_name_plural': 'Lektionen',
                'ordering': ['name'],
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'data',
                'default_manager_name': 'data',
            },
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('concealed', models.BooleanField(default=False, editable=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.media', verbose_name='Medien')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nutzer')),
            ],
            options={
                'verbose_name': 'Abgeschlossen',
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'data',
                'default_manager_name': 'data',
            },
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('concealed', models.BooleanField(default=False, editable=False)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.training', verbose_name='Kurs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nutzer')),
            ],
            options={
                'verbose_name': 'Zugriff',
                'verbose_name_plural': 'Zugriffe',
                'ordering': ['-created'],
                'get_latest_by': 'created',
                'abstract': False,
                'base_manager_name': 'data',
                'default_manager_name': 'data',
            },
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
    ]
