# Generated by Django 4.0.5 on 2022-06-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_media_modified_alter_module_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='prev',
        ),
        migrations.RemoveField(
            model_name='module',
            name='prev',
        ),
        migrations.AlterField(
            model_name='media',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_next', to='application.media', verbose_name='Nächstes'),
        ),
        migrations.AlterField(
            model_name='module',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod_next', to='application.module', verbose_name='Nächstes'),
        ),
    ]
