# Generated by Django 4.0.5 on 2022-06-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_training_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='length',
            field=models.TextField(default='', max_length=50),
        ),
    ]
