# Generated by Django 4.0.5 on 2022-06-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_media_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='length',
            field=models.CharField(default='', max_length=50, verbose_name='Länge'),
        ),
    ]
