# Generated by Django 4.0.5 on 2022-07-05 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_media_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mod_next', to='application.module', verbose_name='Nächstes'),
        ),
    ]
