# Generated by Django 4.0.5 on 2022-07-05 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_module_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_next', to='application.media', verbose_name='Nächstes'),
        ),
    ]
