# Generated by Django 4.0.6 on 2022-10-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_module_options_module_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Gerät', 'verbose_name_plural': 'Geräte'},
        ),
    ]
