# Generated by Django 4.1.3 on 2022-11-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0013_alter_device_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="stick_to_the_plan",
            field=models.BooleanField(default=False, verbose_name="Reihenfolge einhalten"),
        ),
    ]
