# Generated by Django 4.1.4 on 2022-12-30 15:34

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0014_training_stick_to_the_plan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("concealed", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField(verbose_name="Datum")),
                ("start_time", models.TimeField(verbose_name="Startzeit")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                ("link", models.URLField(verbose_name="Meeting-Link")),
            ],
            options={
                "verbose_name": "Termin",
                "verbose_name_plural": "Termine",
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
                "base_manager_name": "data",
                "default_manager_name": "data",
            },
            managers=[
                ("data", django.db.models.manager.Manager()),
            ],
        ),
    ]
