# Generated by Django 4.1.4 on 2023-01-02 21:00

import application.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0016_alter_appointment_options_alter_training_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="description",
            field=application.utils.NonStrippingTextField(verbose_name="Beschreibung"),
        ),
        migrations.AlterField(
            model_name="module",
            name="description",
            field=application.utils.NonStrippingTextField(verbose_name="Beschreibung"),
        ),
    ]
