# Generated by Django 4.1.5 on 2023-01-22 11:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0017_alter_media_description_alter_module_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created"
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                ("concealed", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("courses", models.ManyToManyField(to="application.training")),
            ],
            options={
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkte",
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
                "base_manager_name": "data",
                "default_manager_name": "data",
            },
            managers=[
                ("data", django.db.models.manager.Manager()),
            ],
        ),
    ]
