# Generated by Django 4.1.5 on 2023-01-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0021_alter_media_options_media_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="attachment",
            field=models.FileField(null=True, upload_to="", verbose_name="Anhang"),
        ),
    ]
