# Generated by Django 4.1.5 on 2023-01-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0023_alter_media_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="membership",
            field=models.BooleanField(default=False, verbose_name="Akademie Beziehungskit"),
        ),
        migrations.AddField(
            model_name="product",
            name="teaser",
            field=models.BooleanField(default=False, verbose_name="Beziehungs1x1"),
        ),
    ]
