# Generated by Django 4.1.7 on 2023-03-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0024_product_membership_product_teaser"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="assign_after_days",
            field=models.IntegerField(
                default=0,
                help_text="Wird nach der eingestellten Anzahl an Tagen in der Mitgliedschaft autmatisch freigegeben.",
                verbose_name="Automatisch freigeben",
            ),
        ),
    ]
