# Generated by Django 4.2 on 2023-04-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0025_training_assign_after_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="hide_after_x_days",
            field=models.BooleanField(default=False, verbose_name="Nach 90 Tagen löschen"),
        ),
        migrations.AlterField(
            model_name="training",
            name="assign_after_days",
            field=models.IntegerField(
                default=0,
                help_text="Wird nach der eingestellten Anzahl an Tagen in der Mitgliedschaft automatisch freigegeben.",
                verbose_name="Automatisch freigeben",
            ),
        ),
    ]
