# Generated by Django 4.2.1 on 2023-06-11 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0026_alter_training_assign_after_days"),
        ("application", "0026_training_hide_after_x_days_and_more"),
    ]

    operations = []
