# Generated by Django 4.2.4 on 2023-10-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0026_alter_training_assign_after_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="can_view_appointments",
            field=models.BooleanField(default=False, verbose_name="Termine werden angezeigt"),
        ),
        migrations.AddField(
            model_name="product",
            name="can_view_forum",
            field=models.BooleanField(default=False, verbose_name="Forum wird angezeigt"),
        ),
        migrations.AddField(
            model_name="product",
            name="can_view_zoom_link",
            field=models.BooleanField(default=False, verbose_name="Zoom Link wird angezeigt"),
        ),
        migrations.AlterField(
            model_name="product",
            name="membership",
            field=models.BooleanField(default=False, verbose_name="Intensivzeit"),
        ),
    ]
