# Generated by Django 4.2.4 on 2023-10-08 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("application", "0027_merge_20230611_2051"),
        ("application", "0027_product_can_view_appointments_product_can_view_forum_and_more"),
    ]

    operations = []
