# Generated by Django 4.0.4 on 2022-06-02 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.storages


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0045_alter_access_options_alter_contact_info_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'Zugriff', 'verbose_name_plural': 'Zugriffe'},
        ),
        migrations.AlterModelOptions(
            name='completed',
            options={'verbose_name': 'Abgeschlossen'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('id',), 'verbose_name': 'Medien', 'verbose_name_plural': 'Medien'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Modul', 'verbose_name_plural': 'Module'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Training', 'verbose_name_plural': 'Trainings'},
        ),
        migrations.AlterModelOptions(
            name='uploadprivate',
            options={'verbose_name': 'Privat hochladen', 'verbose_name_plural': 'Privat hochladen'},
        ),
        migrations.AlterField(
            model_name='access',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.training', verbose_name='Training'),
        ),
        migrations.AlterField(
            model_name='access',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
        migrations.AlterField(
            model_name='completed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='completed',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.media', verbose_name='Medien'),
        ),
        migrations.AlterField(
            model_name='completed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
        migrations.AlterField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(storage=webapp.storages.PrivateMediaStorage(), upload_to='', verbose_name='Datei'),
        ),
        migrations.AlterField(
            model_name='media',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_next', to='application.media', verbose_name='Nach'),
        ),
        migrations.AlterField(
            model_name='media',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_prev', to='application.media', verbose_name='Vor'),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(storage=webapp.storages.PrivateMediaStorage(), upload_to='', verbose_name='Vorschaubild'),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='module',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod_next', to='application.module', verbose_name='Nach'),
        ),
        migrations.AlterField(
            model_name='module',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mod_prev', to='application.module', verbose_name='Vor'),
        ),
        migrations.AlterField(
            model_name='module',
            name='thumbnail',
            field=models.ImageField(storage=webapp.storages.PrivateMediaStorage(), upload_to='', verbose_name='Vorschaubild'),
        ),
        migrations.AlterField(
            model_name='training',
            name='thumbnail',
            field=models.ImageField(storage=webapp.storages.PrivateMediaStorage(), upload_to='', verbose_name='Vorschaubild'),
        ),
        migrations.AlterField(
            model_name='zoomlink',
            name='to_show',
            field=models.BooleanField(default=True, verbose_name='Zeigen'),
        ),
        migrations.AlterField(
            model_name='zoomlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nutzer'),
        ),
    ]
