# Generated by Django 4.0.5 on 2022-06-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_alter_access_options_alter_completed_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('flatpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='flatpages.flatpage')),
            ],
            bases=('flatpages.flatpage',),
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('id',), 'verbose_name': 'Lektion', 'verbose_name_plural': 'Lektionen'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Kapitel', 'verbose_name_plural': 'Kapitel'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurse'},
        ),
        migrations.AlterField(
            model_name='access',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.training', verbose_name='Kurs'),
        ),
    ]
