# Generated by Django 4.0.5 on 2022-06-04 17:18

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0046_alter_access_options_alter_completed_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('content', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Inhalt')),
            ],
            options={
                'verbose_name': 'Unterseite',
                'verbose_name_plural': 'Unterseiten',
                'ordering': ['url'],
            },
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ('id',), 'verbose_name': 'Lektion', 'verbose_name_plural': 'Lektionen'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Kapitel', 'verbose_name_plural': 'Kapitel'},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurse'},
        ),
        migrations.AlterField(
            model_name='access',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.training', verbose_name='Kurs'),
        ),
    ]
