# Generated by Django 4.0.5 on 2022-06-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0047_page_alter_media_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
