# Generated by Django 4.0.5 on 2022-06-04 16:38

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0048_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=100, verbose_name='URL')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('content', django_quill.fields.QuillField(blank=True, null=True, verbose_name='Inhalt')),
            ],
            options={
                'verbose_name': 'Unterseite',
                'verbose_name_plural': 'Unterseiten',
                'ordering': ['url'],
            },
        ),
    ]
